name: dependencies_module
description: Modulo responsável pelo gerenciamento das dependencias.
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter
  
  # Externos
  return_success_or_error: ^0.4.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  cloud_firestore: ^3.4.7
  firebase_auth: ^3.8.0
  firebase_remote_config: ^2.0.17
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1

  # Modulos
  design_system_module:
    path: ../design_system_module
  core_module:
    path: ../core_module
  splash_module:
    path: ../splash_module
  login_module:
    path: ../login_module
  home_module:
    path: ../home_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
